### ISSUE TITLE
Low incoming frame rate on Arch Linux

### ISSUE THREAD

**Issue by IceDBorn** [SunshineStream/Sunshine#110]
### Describe the Bug

I'm using sunshine on Arch Linux with a RTX 2060 and I'm getting low incoming frames on Nvidia Shield TV.

### Expected Behavior

60 incoming FPS from network.

### Additional Context

I get frames lower than 60 while the monitor I'm streaming is set to 4K. Setting the monitor to 1440p or 1080p fixes the frame drops. (The 4K monitor is a virtual one created using an HDMI plug). nvidia-utils-nvlax and cuda are installed. I used sunshine on Windows and I'm getting consistent 60 FPS without a single drop.
[Log](https://gist.github.com/IceDBorn/9e611f0276a68b6cab268250437ebdd5)

### Sunshine Host Operating System and Version

Arch Linux

### Architecture

64 bit

### Sunshine Version

0.13.0

### GPU Type

Nvidia

### GPU Model

Geforce RTX 2060

### GPU Driver/Mesa Version

510.54

### Capture Method (Linux Only)

X11

**Comment by ReenigneArcher** [comment]
See here: https://github.com/SunshineStream/Sunshine/discussions/109
