### ISSUE TITLE
Linux/PulseAudio General issue if network on host disconnects.

### ISSUE THREAD

**Issue by GavinDarkglider** [SunshineStream/Sunshine#112]
### Describe the Bug

If using wifi on host, and host wifi disconnects while stream is in session, sunshine aborts, leaving the pulseaudio tunnels available, and set to default, so you have to manually change, or wait for pulseaudio to catch up. In the event of an error like this, sunshine should destroy these tunnels.

Also, side note, but while I am on the subject...... Honestly, it is more work even to get things like 5.1 working even though there are simple tunnels for them, the whole audio routing thing in pulseaudio might need looked at on both sides to fix this. lol. 

### Expected Behavior

On the event that sunshine crashes due to network error, or really anything that causes abort, we need to destroy all pulseaudi tunnels created by stream connect,

### Additional Context

More of an improvement.

### Sunshine Host Operating System and Version

Gentoo

### Architecture

all

### Sunshine Version

latest git at 4b658cd86ba0b7520f6f7cb5b5f07d6775845a81

### GPU Type

Doesnt matter for this issue

### GPU Model

Doesnt matter

### GPU Driver/Mesa Version

Doesnt matter

### Capture Method (Linux Only)

X11

**Comment by ReenigneArcher** [comment]
Please update your issue, specifically this section: `Sunshine Host Operating System and Version`

**Comment by GavinDarkglider** [comment]
> Please update your issue, specifically this section: `Sunshine Host Operating System and Version`

Not sure why this matters at all, but I updated it. Pulseaudio, and audio tunnels arent removed on sunshine abort should be all that matters. This will effect all distros that use pulseaudio, and until sunshine includes code remove any existing sunshine pulseaudio tunnels if abort is called (Usually a network issue on server).

**Comment by HomerSp** [comment]
This should be fixed now, please give it a try if you're able to!
