### ISSUE TITLE
Pipewire does not support "@DEFAULT_MONITOR@"

### ISSUE THREAD

**Issue by Logical-sh** [SunshineStream/Sunshine#127]
### Describe the Bug

If you are running pipewire (rapidly becoming the default for distros and gaming!) the stream will not record the audio.
With the default config, this is caused by sunshine requesting pulse use "@DEFAULT_MONITOR@". This seems to be unsupported in pipewire, causing it to listen to a the first available mic instead. (At least this is what happens on my machine as I could hear myself talk through my vive mic on the far wall!)

### Expected Behavior

Sunshine uses the monitor of the active sink, causing audio to be properly forwarded.

### Additional Context

I think the correct behavior would be to read pulse's sinks and select the default one, and ideally maybe follow the default if changed by the user? Doing this would make switching between stereo and 5.1 and 7.1 and audio duplication on the desktop on the fly all work well. 

### Sunshine Host Operating System and Version

Manjaro Linux (Kernel 5.17)

### Architecture

x64

### Sunshine Version

nightly

### GPU Type

AMD

### GPU Model

6900x

### GPU Driver/Mesa Version

mesa-git

### Capture Method (Linux Only)

KVM

**Comment by Firlaev-Hans** [comment]
Can confirm. I've only ever been able to get audio working by manually piping the desktop audio into Sunshine with a patchbay program like Carla, each and every time I start a stream. Manually setting the sink in Sunshine didn't work either.

**Comment by Logical-sh** [comment]
@Firlaev-Hans I have a PR out that should fix this, but in the mean time if you set the "audio_sink" setting to a monitor it may work for you. 

If you don't want audio duplicated you can try setting the sink to "sink-sunshine-stereo.monitor" in the config.

If you do, use the name of your card plus ".monitor" ex: "alsa_output.pci-0000_0e_00.4.analog-stereo.monitor"

Older versions open the provided name for recording even though the setting and explanation is called sink.
If my pr is accepted it would actually take the proper sink name, and auto switch and record on it.

**Comment by Logical-sh** [comment]
Fixed by pr-130!

**Comment by ReenigneArcher** [comment]
I'll keep this open until it's merged into `master`. Thanks.
