### ISSUE TITLE
Properly document run time dependencies

### ISSUE THREAD

**Issue by ReenigneArcher** [SunshineStream/Sunshine#136]
### Describe the Bug

A common question is about runtime dependencies. Let's properly document these.

deb: https://github.com/SunshineStream/Sunshine/blob/c4054c75a7fdd0c336db326af5a77171db072e49/gen-deb.in#L41

rpm: https://github.com/SunshineStream/Sunshine/blob/c4054c75a7fdd0c336db326af5a77171db072e49/gen-rpm.in#L47

### Additional Context

Is the rpm actually correct?

### Sunshine Host Operating System and Version

-

### Architecture

-

### Sunshine Version

c4054c75a7fdd0c336db326af5a77171db072e49

### GPU Type

-

### GPU Model

-

### GPU Driver/Mesa Version

-

### Capture Method (Linux Only)

-

**Comment by ReenigneArcher** [comment]
@thatsysadmin should the requires section for the rpm include more dependencies? Could this be the cause of #138 ?

**Comment by thatsysadmin** [comment]
It does. I need to figure that out. I need to add ffmpeg as an example, but I'm sure there are a couple more.

I still need to figure out audio.

**Comment by ReenigneArcher** [comment]
> It does. I need to figure that out. I need to add ffmpeg as an example, but I'm sure there are a couple more.
> 
> I still need to figure out audio.

Okay, maybe not a big deal right now. There's an open PR that will use cpack to create the deb, rpm, and adds a windows installer. I'm fairly certain it will include the proper dependencies for the end user (not 100% sure though). #139

**Comment by thatsysadmin** [comment]
While we're talking about this, do you know if the audio works for the Ubuntu packages? I installed the Ubuntu package in a VM a couple of days ago and it couldn't pull the audio in. (KVM emulates an ICH9, which should use Intel drivers.)

**Comment by thatsysadmin** [comment]
I mispoke. It couldn't pull video through the QXL driver. My bad. I'm running on only 4 hours of sleep.
