### ISSUE TITLE
rpm (nightly) install fails on Fedora 35

### ISSUE THREAD

**Issue by joshurawr** [SunshineStream/Sunshine#138]
### Describe the Bug

I've tried on a clean installation on fedora silverblue 35 using `rpm-ostree install sunshine-fedora_35.rpm` and fedora workstation 35 using `dnf install sunshine-fedora_35.rpm`

This is the error I'm seeing in both cases:

```error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides libavcodec.so.58()(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libavcodec.so.58(LIBAVCODEC_58)(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libavdevice.so.58()(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libavformat.so.58()(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libavutil.so.56()(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libavutil.so.56(LIBAVUTIL_56)(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libswscale.so.5()(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
  - nothing provides libswscale.so.5(LIBSWSCALE_5)(64bit) needed by sunshine-0.13.0-1.fc35.x86_64
```

### Expected Behavior

installation succeeds

### Sunshine Host Operating System and Version

Fedora 35

### Architecture

x86-64

### Sunshine Version

nightly

### GPU Type

Nvidia

### GPU Model

Geforce RTX 3080

### GPU Driver/Mesa Version

510

**Comment by ReenigneArcher** [comment]
I think you need to install ffmpeg and/or it's libraries.

**Comment by thatsysadmin** [comment]
@joshurawr 

Can I ask where did you get the package?

**Comment by thatsysadmin** [comment]
@joshurawr 

As @ReenigneArcher said:
You're going to need to install [RPMFusion Free](https://rpmfusion.org/Configuration) and then you can run `sudo dnf install ffmpeg -y` to install ffmpeg. That should be able to get Sunshine to work in a basic configuration (no audio). Video should work however.
