### ISSUE TITLE
Missing AppImage dependencies

### ISSUE THREAD

**Issue by ReenigneArcher** [SunshineStream/Sunshine#146]
### Describe the Bug

The AppImage is missing libraries required to work on some distros. If you test the AppImage on another distro and get an error about a library missing, that isn't in this list, please let us know so we can work on fixing it.

| Library                      | Undefined Symbol                  | Distro / Version          | Fixed at commit / version |
| ---------------------- | -------------------------------- | ----------------------- | ---------------------------- |
| libgio-2.0.so.0          | g_module_open_full                | SteamOS 3                  | https://github.com/AppImage/pkg2appimage/commit/5c8ea76e8df66abd49309b82eec4bdf9aad39eeb |
| libpango-1.0.so.0     | g_memdup2                            | Manjaro Linux             | https://github.com/SunshineStream/Sunshine/commit/84fd2c57661176ab477cb876a2b145e7748f72e3 |
| libpangoft2-1.0.so.0 | pango_matrix_get_slant_ratio | Manjaro Linux             | https://github.com/SunshineStream/Sunshine/commit/84fd2c57661176ab477cb876a2b145e7748f72e3 |

### Additional Context

Replaces #8

### Sunshine Host Operating System and Version

Linux

### Architecture

64 bit

### Sunshine Version

0.13.0

### GPU Type

-

### GPU Model

-

### GPU Driver/Mesa Version

-

### Capture Method (Linux Only)

-

**Comment by lsascha** [comment]
not sure if i should open a new issue or not:
But it seems it is missing something on SteamOS 3 (ArchLinux base) as well.

when trying to run, i get this error:
`./sunshine.AppImage: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

**Comment by ReenigneArcher** [comment]
> not sure if i should open a new issue or not:
> But it seems it is missing something on SteamOS 3 (ArchLinux base) as well.
> 
> when trying to run, i get this error:
> `./sunshine.AppImage: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

That one has been fixed but not available in the latest release yet.

**Comment by cazzoo** [comment]
After some research I can find this issue is occurring on other open-source projects as well (see https://github.com/opentoonz/opentoonz/issues/4406).
Some people already tried to find solutions but unable to get a proper one for now (see https://bbs.archlinux32.org/viewtopic.php?id=3066)

**Comment by ReenigneArcher** [comment]
> After some research I can find this issue is occurring on other open-source projects as well (see [opentoonz/opentoonz#4406](https://github.com/opentoonz/opentoonz/issues/4406)). Some people already tried to find solutions but unable to get a proper one for now (see https://bbs.archlinux32.org/viewtopic.php?id=3066)

@cazzoo So just installing the dependencies on the runner I don't believe is enough, correct?

I think you're on to something with adding `-l /usr/lib/x86_64-linux-gnu/libpango1.0-0.so` to the linuxdeploy command. I think it could work if we know where its installed to? https://github.com/cazzoo/Sunshine/runs/6343522902?check_suite_focus=true#step:6:178

**Comment by cazzoo** [comment]
I'm trying to figure that out but indeed, this path isn't recognized even though this is the path where I can find the lib in an I into 20.04 from docker... 
I tried to install updated deb from 21.10 to 20.04 but there are too many upgraded dependencies so I guess this is not the right approach.
Finally, I tried to get a runner in 21.10 but it just doesn't exist...

**Comment by ReenigneArcher** [comment]
> Unfortunately it didn't work (or maybe I'm doing the wrong way...) See https://github.com/cazzoo/Sunshine/runs/6365779750?check_suite_focus=true for CI output. I've been checking [apk2appimage exclusion list](https://github.com/AppImage/pkg2appimage/blob/a9c85b7e61a3a883f4a35c41c5decb5af88b6b5d/excludelist#L179) but couldn't get something else interesting.

In that case might need to use `dpkg` to locate where it's installed to. See here: https://askubuntu.com/a/115504

**Comment by IgorPuchkov03** [comment]
On Fedora 35:
./sunshine.AppImage: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by ReenigneArcher** [comment]
> On Fedora 35: ./sunshine.AppImage: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full

@IgorPuchkov03 this is already listed... AND already fixed in nightly.

**Comment by cazzoo** [comment]
Ok, good point! I successfully identified the lib path from a docker container.
I successfully added as lib path but now we face another issue:
`/sunshine.AppImage: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: pango_matrix_get_slant_ratio`
I tried to add libpangoft2 as library using the same flag argument but apparently it's not enough despite build is success (see [build #10 on my fork](https://github.com/cazzoo/Sunshine/actions/runs/2302818527)).

I'll try some other stuff later

**Comment by cazzoo** [comment]
Ok, good point! I successfully identified the lib path from a docker container.
I successfully added as lib path but now we face another issue:
`/sunshine.AppImage: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: pango_matrix_get_slant_ratio`
I tried to add libpangoft2 as library using the same flag argument but apparently it's not enough despite build is success (see [build #10 on my fork](https://github.com/cazzoo/Sunshine/actions/runs/2302818527)).

I'll try some other stuff later

**Comment by ReenigneArcher** [comment]
@cazzoo Weird, seems like it packaged correctly according to this: https://github.com/cazzoo/Sunshine/runs/6376358517?check_suite_focus=true#step:6:478

These are just ideas, I have no idea if they will resolve the issue or not.

**Idea 1:**
Can you try these paths instead of the `/usr` path?

https://github.com/cazzoo/Sunshine/runs/6376358517?check_suite_focus=true#step:6:210
https://github.com/cazzoo/Sunshine/runs/6376358517?check_suite_focus=true#step:6:327 (we might need this library?)
https://github.com/cazzoo/Sunshine/runs/6376358517?check_suite_focus=true#step:6:366

**Idea 2:**
Add `libpangocairo-1.0.so.0`. Probably some kind of dependency that's missing for libpango according to these lines.

https://github.com/AppImage/pkg2appimage/blob/a9c85b7e61a3a883f4a35c41c5decb5af88b6b5d/excludelist#L175
https://github.com/AppImage/pkg2appimage/blob/a9c85b7e61a3a883f4a35c41c5decb5af88b6b5d/excludelist#L180

**Idea 3:**
linuxdeploy has plugins: https://github.com/linuxdeploy/linuxdeploy#plugins

Which are listed here: https://github.com/linuxdeploy/awesome-linuxdeploy

I don't know if libpango is related to GLib, but I wonder if using this plugin would resolve the issue: https://github.com/linuxdeploy/linuxdeploy-plugin-gtk

**Lastly**
I don't think you need to manually install these libraries. They seem to be already included. https://github.com/cazzoo/Sunshine/runs/6376358517?check_suite_focus=true#step:3:2360

**Comment by cazzoo** [comment]
Definitely I'll try those.

1# /lib path appears to be the same as for /usr/lib path in docker container (but worth to try anyway):
```
root@e4f1a0acd927:/# ls /lib/x86_64-linux-gnu/libpango-1.0.so.0 -la
lrwxrwxrwx 1 root root 24 Apr 21  2020 /lib/x86_64-linux-gnu/libpango-1.0.so.0 -> libpango-1.0.so.0.4400.7
root@e4f1a0acd927:/# ls -la /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
lrwxrwxrwx 1 root root 24 Apr 21  2020 /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 -> libpango-1.0.so.0.4400.7
```

2# I'll also try to add cairo, because I've seen this dep in linuxdeploy as well.

3# Last resort in case this is not working as expected, but you're right also on this one. It appears pango relies on Glib.

I'll let you know

**Comment by cazzoo** [comment]
@ReenigneArcher Adding libpangocairo helped to move forward, but still I think there are bit not working.
Now it's not related to dependencies anymore but somehow to Sunshine itself (or permissions):
```
./sunshine.AppImage          
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy file: No such file or directory [sunshine.AppImage.config/sunshine.conf] [sunshine.AppImage.config/sunshine.conf]
zsh: IOT instruction (core dumped)  ./sunshine.AppImage
```
(I will not share the coredump extract since it doens't contain anything relevant, thus the error raised is pretty much explicit)

I've been extracting the appImage itself (`./sunshine_orig.AppImage --appimage-extract`) but we cannot find any sunshine.conf file anywhere. Perhaps it's missing the bundle.

![image](https://user-images.githubusercontent.com/1876754/167724353-428a9d64-c554-495c-9699-12afd1de18d4.png)

**Comment by cazzoo** [comment]
Well, maybe that's my fault, I extracted only the AppImage from the zip file but still, I don't understand why the appImage is generated as a Zip and the home & config folders are to be copied manually to the end-user filesystem...
Maybe I'm wrong also here, please advice

**Comment by cazzoo** [comment]
My gosh, just replying myself because I found the way to go. Just extracted the 3 files (appImage + 2 folders) to the same folder and ran the app, it worked!
![image](https://user-images.githubusercontent.com/1876754/167726097-6a87a11c-2900-427c-a2e3-6883ae315359.png)

**Comment by ReenigneArcher** [comment]
> My gosh, just replying myself because I found the way to go. Just extracted the 3 files (appImage + 2 folders) to the same folder and ran the app, it worked!
> ![image](https://user-images.githubusercontent.com/1876754/167726097-6a87a11c-2900-427c-a2e3-6883ae315359.png)
> ![image](https://user-images.githubusercontent.com/1876754/167726185-d6338dce-15db-47a4-b662-29219d7d0ee6.png)

Awesome! I'm trying a different packaging strategy of the AppImage in the add cpack PR.

**Comment by lsascha** [comment]
Just as information:
I patched the latest release AppImage myself according to this description:
https://bbs.archlinux.org/viewtopic.php?pid=1994258#p1994258

which worked perfectly and streaming works nicely now.

Since i don't see any `libgio-2.0.so.0` added in the Pull request, i am not 100 confident that it will also fix the error mentioning `libgio-2.0.so.0` :thinking:

@ReenigneArcher When i should try it with some `nightly`, let me know where i can find the nightly AppImage i should try.

**Comment by ReenigneArcher** [comment]
> Just as information: I patched the latest release AppImage myself according to this description: https://bbs.archlinux.org/viewtopic.php?pid=1994258#p1994258
> 
> which worked perfectly and streaming works nicely now.
> 
> Since i don't see any `libgio-2.0.so.0` added in the Pull request, i am not 100% confident that it will also fix the error mentioning `libgio-2.0.so.0` 🤔
> 
> When i should try it with some `nightly`, let me know where i can find the nightly AppImage i should try.

`libgio-2.0.so.0` was fixed upstream as indicated by the table in the original comment.

You can test these.

https://github.com/SunshineStream/Sunshine/actions/runs/2303519447 (artifact: sunshine-appimage)
https://github.com/SunshineStream/Sunshine/actions/runs/2310958227 (artifact: sunshine-linux ... I'm aware the paths are not correct)

**Comment by lsascha** [comment]
@ReenigneArcher
Thanks. Tested the AppImage nightly from the artifact and streaming works perfectly fine without patching the AppImage. 👍

**Comment by ReenigneArcher** [comment]
@lsascha I'm guessing you only tested the first one I linked?

**Comment by lsascha** [comment]
> @lsascha I'm guessing you only tested the first one I linked?

Yes. only tested the first one, since SteamOS more or less requires AppImages or Flatpaks. Didn't check that the other file includes an AppImage as well
