### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Donald-Schickel-Aspiritech** [SunshineStream/Sunshine#159]
### Describe the Bug

The compilation instructions for Linux states to clone from 
git clone https://github.com/loki-47-6F-64/sunshine.git --recurse-submodules

and the windows compilation instructions states to clone from 
git clone https://github.com/loki-47-6F-64/sunshine.git --recursive

As Loki's repo is abandoned the instructions should be updated to use the repo that is currently under active development

### Expected Behavior

Linux should clone from 
git clone https://github.com/SunshineStream/Sunshine.git  --recurse-submodules

and Windows should clone from 
git clone https://github.com/SunshineStream/Sunshine.git --recursive

### Sunshine Host Operating System and Version

n/a

### Architecture

n/a

### Sunshine Version

n/a

### GPU Type

n/a

### GPU Model

n/a

### GPU Driver/Mesa Version

n/a

**Comment by don17sch** [comment]
I made a mistake and created this issue on a work account. This is the account I use outside of work

**Comment by ReenigneArcher** [comment]
Documentation has moved here: https://sunshinestream.readthedocs.io/en/nightly/

**Comment by don17sch** [comment]
ok thank you for that.
