### ISSUE TITLE
Starting RTSP handshake failed: Error 500

### ISSUE THREAD

**Issue by pokemaster974** [SunshineStream/Sunshine#161]
### Describe the Bug

I download the zip from the github repo
I modify the .conf (or the UI) to change the famiy of ports from 47989 to 37989
I've added ports rules into my Windows firewall
TCP 37984, 37989, 38010
UDP 37998, 37999, 38000, 38002, 38010
I've opened the same ports into my routeur interface
I launch the sunshine.exe

I launch the https://localhost:37990/pin
I paired my moonlight client with success
I launch the desktop session and got an error :
Starting RTSP handshake failed: Error 500
Check your firewall and portforwarding rules for port(s) : TCP 48010, UDP 48000, UDP 48010

Log from moonlight client :
00:01:39 - SDL Info (0): RTSP port: 38010
00:01:39 - SDL Info (0): Initializing platform...
00:01:39 - SDL Info (0): WLAN interface 0 is now in low latency mode
00:01:39 - SDL Info (0): done
00:01:39 - SDL Info (0): Resolving host name...
00:01:39 - SDL Info (0): done
00:01:39 - SDL Info (0): Initializing audio stream...
00:01:39 - SDL Info (0): done
00:01:39 - SDL Info (0): Starting RTSP handshake...
00:01:39 - SDL Info (0): Audio port: 38000
00:01:39 - SDL Info (0): Video port: 37998
00:01:39 - SDL Info (0): Control port: 37999
00:01:39 - SDL Info (0): RTSP ANNOUNCE request failed: 500
00:01:39 - SDL Info (0): failed: 500
00:01:40 - SDL Info (0): TCP port 48010 test successful
00:01:40 - SDL Info (0): UDP port 48000 test successful
00:01:40 - SDL Info (0): UDP port 48010 test successful
00:01:40 - SDL Info (0): Cleaning up audio stream...
00:01:40 - SDL Info (0): done
00:01:40 - SDL Info (0): Cleaning up platform...
00:01:40 - SDL Info (0): done

### Expected Behavior

Using RTSP in the family ports reporting into the sunshine conf

### Additional Context

I would like to change the family port because of ports blocking in some places I would like to use it

### Sunshine Host Operating System and Version

Windows 10

### Architecture

64 bit

### Sunshine Version

0.13.0

### GPU Type

Nvidia

### GPU Model

GeForce GTX970

### GPU Driver/Mesa Version

512.77

**Comment by ReenigneArcher** [comment]
Where do you want to use it?

If it's external to your LAN, you can always keep sunshine on the default port, then forward the ports you want to use externally to the default port internally. This would be done in your router.

**Comment by pokemaster974** [comment]
Soory, checked more precisely what the origin of error 500 with verbose 0

```
[2022:05:13:09:12:01]: Error: Couldn't bind Control server to port [37999], likely another process already bound to the port
[2022:05:13:09:12:01]: Error: Failed to start a streaming session
[2022:05:13:09:12:01]: Debug: ---Begin Response---
RTSP/1.0 500 Internal Server Error
CSeq: 6
```

So it's used by another process (but I don't know which....)
So I changed again the ports to 27999 and it works

I closed the issue as it's solved.

Regards
