### ISSUE TITLE
Windows Installer should automatically install the `sunshinevc` service

### ISSUE THREAD

**Issue by sitiom** [SunshineStream/Sunshine#199]
### Describe the Bug

With the `sunshinevc` component selected, The installer does not automatically install the `sunshinevc` service.

### Expected Behavior

It should automatically install the `sunshinevc` service.

### Additional Context

https://github.com/SunshineStream/Sunshine/discussions/198

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

512.95

**Comment by ReenigneArcher** [comment]
Dude... I don't have time to manage all of this github activity you're creating. One issue is enough, they are not significantly different issues. I've combined this with your other issue.
