### ISSUE TITLE
Warning: Couldn't setup connection to ViGEm for gamepad support [E0000001]

### ISSUE THREAD

**Issue by DocMAX** [SunshineStream/Sunshine#208]
### Describe the Bug

Warning: Couldn't setup connection to ViGEm for gamepad support [E0000001]

### Expected Behavior

No error

### Sunshine Host Operating System and Version

Windows 11 22H2

### Architecture

64bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 3080

### GPU Driver/Mesa Version

512.95

**Comment by DocMAX** [comment]
I am very stupid. Didn't install ViGEmBus.

**Comment by ReenigneArcher** [comment]
Please note we use this issue tracker for bug reports only. If you need support talk to us on Discord or in Discussions.
