### ISSUE TITLE
Linux NVENC (Kepler): "no kernel image is available for execution on the device"

### ISSUE THREAD

**Issue by opm0** [SunshineStream/Sunshine#245]
### Describe the Bug

If you install a release .deb and try to use NVENC on Linux with a Kepler card, you will get an error saying `cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device`

### Additional Context

There's no error if you compile it yourself.

### Sunshine Host Operating System and Version

Ubuntu 22.04

### Architecture

x86-64

### Sunshine Version

0.14.0

### GPU Type

NVIDIA

### GPU Model

GeForce GTX 660 Ti (2GB)

### GPU Driver/Mesa Version

470.129.06

**Comment by ReenigneArcher** [comment]
Your gpu doesn't support nvenc. See here: https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by ReenigneArcher** [comment]
You can reach us on discord... do not spam our issues
