### ISSUE TITLE
AMD APU 4800U and VAAPI

### ISSUE THREAD

**Issue by DocMAX** [SunshineStream/Sunshine#255]
### Describe the Bug

With the APU described in the title streaming kind of works, but at very low bitrate (?). I see a picture with lots of compression as if the compression level is set too high. I'm using VAAPI and i can't see a way to adjust the bitrate (if this is the problem).

### Expected Behavior

Crystal clear, sharp picture.

### Additional Context

Tried differend codec H264/HVEC.

### Sunshine Host Operating System and Version

Arch Linux 5.18.11

### Architecture

64-bit

### Sunshine Version

0.14

### GPU Type

AND 4800U

### GPU Model

Integrated Graphics with VAAPI (AMD RENOIR)

### GPU Driver/Mesa Version

Mesa 22.1.3 / AMD RENOIR (LLVM 14.0.6, DRM 3.46, 5.18.12-arch1-1)

### Capture Method (Linux Only)

PipeWire/X11

**Comment by ReenigneArcher** [comment]
Have a look through the encoder settings: https://sunshinestream.readthedocs.io/en/latest/about/advanced_usage.html#encoding

**Comment by DocMAX** [comment]
Thank you i allready tried to change some settings but nothing happens on the picture quality.

**Comment by DocMAX** [comment]
OK stupid me. Seems i had to adjust the bitrate on the client and not the server (sunshine). I set 20000 bps/s and it looks much nicer. Only i have some green and blue screen flashes here and there but that doesnt bother me.
