### ISSUE TITLE
Add MacOS package

### ISSUE THREAD

**Issue by ReenigneArcher** [SunshineStream/Sunshine#40]
**Describe the bug**

MacOS version not available

**Additional context**

There is an under development version here: https://github.com/abusse/sunshine/tree/macos-dev

**Comment by ReenigneArcher** [comment]
@abusse would you be interested in doing a PR to this repo for Mac support?

It would be a somewhat manual process, and I apologize for that, as this is an import (not a fork) of Loki's repo.

Not sure the current state of your branch. If it's working, even if just experimentally I think it would be nice to include in our next release.

**Comment by abusse** [comment]
Ah yes, I noticed that Loki seems to have disappeared 😕 The Mac branch is working and I'm basically just collecting bugs but so far not to many have come up (currently just one open todo), so it should be fine to merge. When I have some time, I will try to rebase it on top of this repository.

**Comment by ReenigneArcher** [comment]
> Ah yes, I noticed that Loki seems to have disappeared 😕 The Mac branch is working and I'm basically just collecting bugs but so far not to many have come up (currently just one open todo), so it should be fine to merge. When I have some time, I will try to rebase it on top of this repository.

Amazing! Even though I don't use mac personally, definitely appreciate all your work!

**Comment by abusse** [comment]
@ReenigneArcher I successfully rebased on `nightly` without any major issue and I'm in the process to prepare the PR. However, there is one question that I'm currently facing: Do you want me to squash the 30-40 commits I currently have or can I keep them around? I strongly prefer the latter option as it will probably make it easier to understand in the future why certain decisions were made the way they are.

**Comment by ReenigneArcher** [comment]
> @ReenigneArcher I successfully rebased on `nightly` without any major issue and I'm in the process to prepare the PR. However, there is one question that I'm currently facing: Do you want me to squash the 30-40 commits I currently have or can I keep them around? I strongly prefer the latter option as it will probably make it easier to understand in the future why certain decisions were made the way they are.

That's awesome! I have no problem with either method. If you prefer to have all of the original commits that is fine with me. I don't know how much trouble that would be to be honest.

**Comment by ReenigneArcher** [comment]
@abusse Had a peek at the rebase... trying to prepare myself for what I'll need to update in the CI workflow. Looking good!

One question, can the [apps_macos.json](https://github.com/abusse/Sunshine-1/blob/macos-dev/assets/apps_mac.json) have Desktop and Steam BigPicture added similar to the [windows](https://github.com/abusse/Sunshine-1/blob/macos-dev/assets/apps_windows.json) and [linux](https://github.com/abusse/Sunshine-1/blob/macos-dev/assets/apps_linux.json) files? I guess technically Desktop is not in the windows file, but still appears in clients.

**Comment by abusse** [comment]
@ReenigneArcher saw your additional comment just now after submitting the pull request 😞

We can probably add that, but so far the support only includes streaming the entire desktop. Streaming a specific window should not be to hard, but requires some refactoring as I hadn't considered that so far. Also lunching a different application would be something I have to look into.

Regarding the packaging, at the moment, my strategy would be to have a Port or Brew file. I was already looking into a Github flow to have automatic builds but back then Github didn't have the latest MacOS version as build host, which would have been required. But that would also only result in a CLI application. We would need a little bit more effort to have an actual App bundle. So far, I only have done CLI Applications for MacOS, so this would also need some more work from my side.

I would suggest once my pull request is merged, we create tickets and I (or other volunteers) can then work on them and keep track of the progress.

**Comment by ReenigneArcher** [comment]
> @ReenigneArcher saw your additional comment just now after submitting the pull request 😞
> 
> We can probably add that, but so far the support only includes streaming the entire desktop. Streaming a specific window should not be to hard, but requires some refactoring as I hadn't considered that so far. Also lunching a different application would be something I have to look into.
> 
> Regarding the packaging, at the moment, my strategy would be to have a Port or Brew file. I was already looking into a Github flow to have automatic builds but back then Github didn't have the latest MacOS version as build host, which would have been required. But that would also only result in a CLI application. We would need a little bit more effort to have an actual App bundle. So far, I only have done CLI Applications for MacOS, so this would also need some more work from my side.
> 
> I would suggest once my pull request is merged, we create tickets and I (or other volunteers) can then work on them and keep track of the progress.

Sounds good. And I agree, this is a great first step, we can improve over time! I am running the build now to make sure nothing breaks on linux/windows side.

**Comment by abusse** [comment]
@ReenigneArcher Can we have a label `os:macOS` (and have this ticket the first to tag)? So I can easily filter once the issues for the macOS port start to role in.

**Comment by ReenigneArcher** [comment]
> @ReenigneArcher Can we have a label `os:macOS` (and have this ticket the first to tag)? So I can easily filter once the issues for the macOS port start to role in.

Yes, absolutely. I just added those labels because I wanted to label all the Arch Linux issues, haha.

**Comment by ReenigneArcher** [comment]
@abusse I added the label for Mac. Also would you be interested in being on the org team? We could use someone with your experience level. If not, no worries. Also we have a discord, might be easier to discuss development topics there if you are on discord. https://sunshinestream.github.io/discord_join/
