### ISSUE TITLE
Support for pipewire-pulse

### ISSUE THREAD

**Issue by KuleRucket** [SunshineStream/Sunshine#46]
**Describe the bug**
On Arch you can use pipewire-pulse in place of pulseaudio as a pulseaudio compatible interface to pipewire. Using pipewire-pulse will completely replace the pulseaudio package. According to the config file and readme, pipewire is supported however when I try to use it I get the core dump exactly as documented in https://github.com/loki-47-6F-64/sunshine/issues/216

**To Reproduce**
$ sudo pacman -Suy pipewire-pulse
allow removal of conflicting pulseaudio package
start sunshine

**Expected behavior**
Does not core dump, pipewire supported

**Screenshots**
See https://github.com/loki-47-6F-64/sunshine/issues/216

**Host**
 - OS: Arch Linux
 - Architecture: 64 bit
 - Version: 0.11.1
 - GPU Type: Nvidia
 - GPU Model: RTX 3070
 - GPU Driver/Mesa Version: 510.47.03
 - Capture method (Linux only): PipeWire + NvFBC

**Comment by ReenigneArcher** [comment]
Related to #39

**Comment by HomerSp** [comment]
Does it work if you set audio_sink in the config file to the default sink (pactl info will give you the name)?
I'm using KDE neon myself, and while it doesn't crash it doesn't actually capture any audio - but setting a specific monitor does make it work. It seems like pipewire-pulse doesn't support @DEFAULT_MONITOR@ properly.

**Comment by KuleRucket** [comment]
Actually yes, by setting audio sink to the default sink (or default source), I don't get the crash. When I tried this before I think I got the crash whether I set audio_sink or not.

With audio_sink set I now get a brief whitescreen and then moonlight disconnects with "Connection Terminated".

**Comment by ReenigneArcher** [comment]
> Actually yes, by setting audio sink to the default sink (or default source), I don't get the crash. When I tried this before I think I got the crash whether I set audio_sink or not.

Is this issue resolved?

**Comment by ReenigneArcher** [comment]
> The crash is yes, but it still doesn't actually work so it could be closed and a new ticket be created with a new problem description.

Okay, I'm going to close this. If it something that needs to be addressed in sunshine code please submit a new issue. If it is something related to dependencies in Arch, I'd redirect you to the AUR package. Thanks!
