### ISSUE TITLE
Autostart does not work with SDDM/KDE/X11

### ISSUE THREAD

**Issue by pogojotz** [SunshineStream/Sunshine#78]
### Describe the Bug

Using SDDM/KDE/X11 the user service enabled with `systemctl enable --user sunshine.service` does not start after login in SDDM.

The reason for this seem to be the (continued) lack of support for the `graphical-session.target` in SDDM (https://github.com/sddm/sddm/issues/1044). I believe the target description in systemd.special(7) is more of desired state and less the reality.

Several sources on the internet (having similar problems with their service files including `WantedBy=graphical-session.target`) suggest to use `default.target`, but I guess this is not a viable solution for Sunshine.

### Expected Behavior

Service starts after user login in SDDM

### Additional Context

`systemctl list-units --type=target --all --user` in a KDE session gives:
```
  UNIT                          LOAD      ACTIVE   SUB    DESCRIPTION                   
  basic.target                  loaded    active   active Basic System
● blockdev@dev-nvme0n1p2.target not-found inactive dead   blockdev@dev-nvme0n1p2.target
● blockdev@dev-nvme0n1p3.target not-found inactive dead   blockdev@dev-nvme0n1p3.target
● blockdev@dev-nvme0n1p4.target not-found inactive dead   blockdev@dev-nvme0n1p4.target
  default.target                loaded    active   active Main User Target
  graphical-session.target      loaded    inactive dead   Current graphical user session
  paths.target                  loaded    active   active Paths
  shutdown.target               loaded    inactive dead   Shutdown
  sockets.target                loaded    active   active Sockets
  sound.target                  loaded    inactive dead   Sound Card
  timers.target                 loaded    active   active Timers
```

### Sunshine Host Operating System and Version

Arch Linux

### Architecture

x86_64

### Sunshine Version

0.13.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070

### GPU Driver/Mesa Version

510.54

### Capture Method (Linux Only)

X11

**Comment by KuleRucket** [comment]
Thanks I've been trying to work this one out for a while. If sddm refuses to support graphical-session.target, then what mechanism does KDE use to start user services after login? Also I wonder if there is some change I can make to my own SDDM/systemd to make this work the way I want even if not offically supported.

**Comment by pogojotz** [comment]
I couldn't find anything concrete on this topic. KDE seems to fully rely on XDG desktop entries. There are two solutions for me right now, which both have their drawbacks:

1. Create a desktop file and enable autostart for it in the KDE settings  
`~/.local/share/application/sunshine.autostart.desktop`:
```
[Desktop Entry]
Name=Sunshine
GenericName=Desktop Streaming
Exec=/usr/bin/sunshine ${XDG_CONFIG_HOME}/sunshine/sunshine.conf
Terminal=false
```
2. Use `systemctl edit --user sunshine.service` to set the install target to default.target:
```
[Install]
WantedBy=default.target
```

Drawbacks:
(1) not using systemd. Some ppl might actually prefer this 😄 but I like the control you get with systemd
(2) starts also if you just login to a shell without any graphical session... This is not actually an issue for me, but this might be undesirable for some.

**Comment by KuleRucket** [comment]
Similarly to the first option I now have two scripts as a workaround

~/bin/login
```
#!/bin/bash
systemctl --user start sunshine
```
~/bin/logout
```
#!/bin/bash
systemctl --user stop sunshine
```
In the KDE Autostart settings, I have added these under "Login Scripts" and "Logout Scripts" rather than using .desktop files under the startup Applications. This is working great.

**Comment by Jonathan34** [comment]
I confirm this does not start sunshine.service on startup after xdg on ubuntu Jammy.
I have set an autostart script to run `systemctl --user start sunshine` and then the service starts.

**Comment by shiftonetothree** [comment]
@KuleRucket 
Thank you, solve my problem on ubuntu 22.04, on ubuntu 22.04, use gnome-session-properties to add ~/bin/loign to autostart
