### ISSUE TITLE
`libgio-2.0.so.0` undefined symbol (AppImage)

### ISSUE THREAD

**Issue by ReenigneArcher** [SunshineStream/Sunshine#8]
There have been reports in the moonlight discord that the AppImage does not run on all linux distros.
See here: https://github.com/loki-47-6F-64/sunshine/issues/267#issuecomment-997034001

Most likely the AppImage is missing runtime dependencies.

This may be useful: https://bbs.archlinux.org/viewtopic.php?pid=1994258#p1994258

**Comment by ReenigneArcher** [comment]
@thatsysadmin Could you test this build of the AppImage to see if it's still complaining about missing `libgio-2.0.so.0`?

https://github.com/SunshineStream/Sunshine/suites/5676028598/artifacts/186354212

**Comment by thatsysadmin** [comment]
@ReenigneArcher 

It complains of `libgobject-2.0.so.0`. Had an exit code of 127.

`sudo ./sunshine.AppImage`

```
[sudo] password for h: 
Setting $HOME to /home/h/Downloads/sunshine-AppImage/sunshine-appimage/sunshine/sunshine.AppImage.home
Setting $XDG_CONFIG_HOME to /home/h/Downloads/sunshine-AppImage/sunshine-appimage/sunshine/sunshine.AppImage.config
./sunshine.AppImage: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
```

**Comment by ReenigneArcher** [comment]
> @ReenigneArcher 
> 
> It complains of `libgobject-2.0.so.0`. Had an exit code of 127.
> 
> `sudo ./sunshine.AppImage`
> 
> ```
> [sudo] password for h: 
> Setting $HOME to /home/h/Downloads/sunshine-AppImage/sunshine-appimage/sunshine/sunshine.AppImage.home
> Setting $XDG_CONFIG_HOME to /home/h/Downloads/sunshine-AppImage/sunshine-appimage/sunshine/sunshine.AppImage.config
> ./sunshine.AppImage: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
> ```

Okay thanks... Slightly different than before.
https://github.com/loki-47-6F-64/sunshine/issues/267#issuecomment-997034001

**Comment by ReenigneArcher** [comment]
@thatsysadmin sorry for being a pain... any chance you could test this one? Apparently `linuxdeploy` binaries were rebuilt recently which resolves this issue (same issue I believe): https://github.com/linuxdeploy/linuxdeploy/issues/197

https://github.com/SunshineStream/Sunshine/suites/5689951680/artifacts/187155592

**Comment by thatsysadmin** [comment]
@ReengineArcher

Nope. Same error. 

`sudo ./sunshine.AppImage`

```
[sudo] password for h: 
Setting $HOME to /tmp/MicrosoftEdgeDownloads/7c5f79ff-31b3-49b5-ad6b-79cf3548f32f/sunshine-appimage (1)/sunshine/sunshine.AppImage.home
Setting $XDG_CONFIG_HOME to /tmp/MicrosoftEdgeDownloads/7c5f79ff-31b3-49b5-ad6b-79cf3548f32f/sunshine-appimage (1)/sunshine/sunshine.AppImage.config
./sunshine.AppImage: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
```

FYI, The file the CI spat out that you gave me is compressed twice.

**Comment by ReenigneArcher** [comment]
@thatsysadmin okay thanks. I will open an issue against `linuxdeploy` tomorrow to see if they can assist.

I'm aware of the double archive, and I know it's annoying. The reason for that is if the individual files are uploaded to artifacts directly, they lose any execution permissions.

**Comment by ReenigneArcher** [comment]
There is a new commit to pkg2appimage that I believe will resolve this issue.

https://github.com/AppImage/pkg2appimage/commit/5c8ea76e8df66abd49309b82eec4bdf9aad39eeb

**Comment by ReenigneArcher** [comment]
@thatsysadmin mind testing this one? https://github.com/SunshineStream/Sunshine/actions/runs/2049605403

**Comment by thatsysadmin** [comment]
Nope. Same issue as before.

![image](https://user-images.githubusercontent.com/65380846/160326124-375c11b4-566d-4918-9e7e-f901eac8f5c3.png)

**Comment by thatsysadmin** [comment]
Thought I'd try my laptop which isn't as used heavily (so "cleaner"), to rule out my desktop OS install; same error.

![image](https://user-images.githubusercontent.com/65380846/160326619-c6b2188c-8e5e-4822-b06b-2e36a1ecc9f6.png)

**Comment by ReenigneArcher** [comment]
https://github.com/linuxdeploy/linuxdeploy/issues/198

**Comment by ReenigneArcher** [comment]
Based on these warnings, I am not sure if the issue is fixed or not. https://github.com/SunshineStream/Sunshine/runs/5839581100?check_suite_focus=true#step:7:740

If you could try again that would be great. https://github.com/SunshineStream/Sunshine/actions/runs/2098245926

**Comment by thatsysadmin** [comment]
![image](https://user-images.githubusercontent.com/65380846/161867953-a146ccf3-b2e0-4f69-8ce5-d010e79fafeb.png)

Different error this time. ```symbol lookup error: /lib64/libpango-1.0.so.0: undefined symbol: g_memdup2```

**Comment by ReenigneArcher** [comment]
I guess that's progress, haha.

At this point, I'm guessing the missing libraries need to be manually added to the AppImage. If anyone would like to take on this issue, that would be appreciated. AppImage build is completely done inside the CI.yml workflow file.

**Comment by cazzoo** [comment]
Just tried to add libpango-1.0 to the appImage but the issue is the same.
Workflow reported that libpango is already installed.
```
libpango-1.0-0 is already the newest version (1.44.7-2ubuntu4).
libpango-1.0-0 set to manually installed.
```
After starting the AppImage, the error is the same
