### ISSUE TITLE
AMDVCE not working on 0.13.0

### ISSUE THREAD

**Issue by cleciusjm** [SunshineStream/Sunshine#89]
### Describe the Bug

Using windows 10, with already working sunshine installation at 0.11.1 (loki version), after update to 0.13.0 i've this error:

![sunshine-fail](https://user-images.githubusercontent.com/3534690/157722810-4f0db45f-bf8d-4a93-955e-4575010e19e0.png)

Using 'auto' encoder option, sunshine fallback to software encoder, and gives me a blackscreen, with or without HEVC

### Expected Behavior

To boot and stream using AMDVCE like was working on 0.11.1

### Additional Context

I've cleaned up config files to ensure that isn't config incompatibility, and the error remains.

### Sunshine Host Operating System and Version

windows 10

### Architecture

64 bit

### Sunshine Version

0.13.0

### GPU Type

AMD

### GPU Model

RX 5600XT 6GB

### GPU Driver/Mesa Version

Adrenalin 22.2.3

**Comment by ReenigneArcher** [comment]
Can you try these versions from this repo and let me know if the results are different?

https://github.com/SunshineStream/Sunshine/releases/tag/v0.11.1
https://github.com/SunshineStream/Sunshine/releases/tag/v0.12.0

**Comment by cleciusjm** [comment]
Same with both, but now retrying loki's version, same problem too, i don't know what happened, but backing to working version not work anymore.

**Comment by cleciusjm** [comment]
Here dxgi-info if it helps

PS E:\utils\sunshineTest> .\tools\dxgi-info.exe
====== ADAPTER =====
Device Name      : AMD Radeon RX 5600 XT
Device Vendor ID : 0x00001002
Device Device ID : 0x0000731F
Device Video Mem : 5758 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16341 MiB

    ====== OUTPUT ======
    Output Name       : \\.\DISPLAY2
    AttachedToDesktop : yes
    Resolution        : 2560x1080

    Output Name       : \\.\DISPLAY1
    AttachedToDesktop : yes
    Resolution        : 1080x1920

====== ADAPTER =====
Device Name      : AMD Radeon RX 5600 XT
Device Vendor ID : 0x00001002
Device Device ID : 0x0000731F
Device Video Mem : 5758 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16341 MiB

    ====== OUTPUT ======
====== ADAPTER =====
Device Name      : Microsoft Basic Render Driver
Device Vendor ID : 0x00001414
Device Device ID : 0x0000008C
Device Video Mem : 0 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 16341 MiB

    ====== OUTPUT ======

**Comment by cleciusjm** [comment]
Seems to be the same [of this issue](https://github.com/loki-47-6F-64/sunshine/issues/257)

**Comment by ReenigneArcher** [comment]
> Same with both, but now retrying loki's version, same problem too, i don't know what happened, but backing to working version not work anymore.

v0.11.1 matches Loki's, so that's why I wanted you to check that one as well.
